language: node_js
node_js:
- 9
branches:
  only:
  - master
cache:
  directories:
    - node_modules
install:
- npm install
- npm install hexo-cli -g
script:
- npm install hexo-deployer-git --save
- hexo clean
- hexo generate -d
before_install:
- openssl aes-256-cbc -K $encrypted_5bc884c9e074_key -iv $encrypted_5bc884c9e074_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "kuops"
- git config --global user.email opshsy@gmail.com

