language: node_js
node_js:
- 9
branches:
  only:
  - master
install:
- npm install hexo-cli -g
- npm install
- git clone https://github.com/yangg/hexo-theme-even.git themes/even
script:
- deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_5bc884c9e074_key -iv $encrypted_5bc884c9e074_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
